name: "CI Build"

on:
  push:
    # Run on all branches except master, which is handled by the prerelease workflow
    branches-ignore:
      - 'master'
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    name: "Build and test"
    uses: ./.github/workflows/build.yml
    # Note: secrets must be explicitly passed to reusable workflows if needed.
    # secrets: inherit
