name: "Pre-release"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    name: "Run Build and Test Matrix"
    uses: ./.github/workflows/build.yml

  publish:
    name: "Publish Pre-release"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all build artifacts from build job
        uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: release-assets
          merge-multiple: true

      - name: Create 'continuous' Pre-release
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/*
          tag_name: "continuous"
          name: "Continuous Build (Pre-release)"
          body: "This is a continuous build which may be unstable."
          prerelease: true
