name: "Tagged Release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: "Run Build and Test Matrix"
    uses: ./.github/workflows/reusable-build.yml

  publish:
    name: "Publish Tagged Release"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all build artifacts from build job
        uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: release-assets
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/*
          prerelease: false
